spring:
    application:
        name: lhtsharding
    sharding:
        datasource:
            db0:
                url: jdbc:mysql://47.108.190.202:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root
            db1:
                url: jdbc:mysql://47.108.190.202:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
                username: root
                password: root